// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gomud

import (
	"github.com/cory-johannsen/gomud/engine"
)

// Injectors from wire.go:

func InitializeEngine() (*engine.Engine, error) {
	config, err := engine.NewConfigFromEnv()
	if err != nil {
		return nil, err
	}
	server := engine.NewServer(config)
	engineEngine := engine.NewEngine(config, server)
	return engineEngine, nil
}
