// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gomud

import (
	"github.com/cory-johannsen/gomud/internal/engine"
)

// Injectors from wire.go:

func InitializeEngine() (*engine.Engine, error) {
	config, err := engine.NewConfigFromEnv()
	if err != nil {
		return nil, err
	}
	database, err := engine.NewDatabase(config)
	if err != nil {
		return nil, err
	}
	server := engine.NewServer(config, database)
	engineEngine := engine.NewEngine(config, server)
	return engineEngine, nil
}
