// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cory-johannsen/gomud/internal/config"
	"github.com/cory-johannsen/gomud/internal/engine"
	"github.com/cory-johannsen/gomud/internal/generator"
	"github.com/cory-johannsen/gomud/internal/loader"
	"github.com/cory-johannsen/gomud/internal/storage"
)

// Injectors from wire.go:

func InitializeEngine() (*engine.Engine, error) {
	configConfig, err := config.NewConfigFromEnv()
	if err != nil {
		return nil, err
	}
	database, err := storage.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	players := storage.NewPlayers(database)
	appearanceLoader := loader.NewAppearanceLoader(configConfig)
	traitLoader := loader.NewTraitLoader(configConfig)
	backgroundLoader := loader.NewBackgroundLoader(configConfig, traitLoader)
	teamLoader := loader.NewTeamLoader(configConfig)
	loaders := loader.NewLoaders(appearanceLoader, backgroundLoader, traitLoader, teamLoader)
	playerGenerator := generator.NewPlayerGenerator(appearanceLoader, backgroundLoader)
	server := engine.NewServer(configConfig, database, players, loaders, playerGenerator)
	engineEngine := engine.NewEngine(configConfig, server)
	return engineEngine, nil
}
