name: {{ .name }}
jobs:
{{- range .jobs }}
  - {{ .name }}:
      name: "{{ .name }}"
      profession: "{{ .profession }}"
      traits:
      {{- range .traits }}
      - {{ .name }}:
          name: "{{ .name }}"
          description: "{{ .description }}"
          effect: "{{ .effect }}"
      {{- end }}
      drawbacks:
      {{- range .drawbacks }}
      - {{ .name }}:
          name: "{{ .name }}"
          description: "{{ .description }}"
          effect: "{{ .effect }}"
      {{- end }}
      equipment:
      {{- range .equipment }}
        - {{ . }}
      {{- end }}
      money: {{ .money }}
  {{- end }}